package com.example.aadk3_social_app.data

// Every post will have a unique ID that will be generated by us at the time of Posting
data class Post(
    val imageUrl: String = "",
    val description: String = "",
    val likes: MutableList<String> = mutableListOf(),
    val createdAt: Long = 0L
)
