package com.example.aadk3_social_app.data

// Every user will have a Unique UserID (generated by Firebase Auth)
data class User(
    val fullName: String = "",
    val email: String = "",
    val about: String = "",
    var profilePic: String = "",
    val followers: MutableList<String> = mutableListOf(),
    val followings: MutableList<String> = mutableListOf(),
    val posts: MutableList<String> = mutableListOf()
)

/*
Dashboard ->
Search -> Users collection
Create -> Posts collection
Profile Page -> Users as well as Posts Collection
    fetching a list of uids of the posts
    fetching the entire post objects from these ids
    fetching the urls amd using glide to display the images
 */
